"""Add description, category, difficulty, location to Skill

Revision ID: 403befd70c32
Revises: 
Create Date: 2025-08-21 15:40:27.329652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403befd70c32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_skills_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_location'), ['location'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_location'))
        batch_op.drop_index(batch_op.f('ix_skills_difficulty'))
        batch_op.drop_index(batch_op.f('ix_skills_category'))
        batch_op.drop_column('location')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('category')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
